{
    'name': 'BOQ TOOL',
    'version': '2.0',
    'category': 'Project',
    'summary': 'CBOQ & SBOQ Operations',
    'author': 'Nokia',
    # 'depends': ['base'],
    'depends': ['base', 'web', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/home.xml',
        'views/login.xml',
        'views/view_cboq_pick_site.xml',
        'views/view_cboq_entry.xml',
        'views/view_cboq_overview.xml',
        'views/view_sboq_pick_site.xml',
        'views/view_sboq_entry.xml',
        'views/view_sboq_overview.xml',
        'views/view_review_list.xml',
        'views/view_review_detail.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'BOQ/static/src/css/login.css',
            'BOQ/static/src/css/home.css',
            'BOQ/static/src/css/site_config.css',
            'BOQ/static/src/css/create_cboq.css',
            'BOQ/static/src/js/create_cboq.js',
            'BOQ/static/src/js/create_sboq.js',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
